# permissions for end users to view nginxsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxset-viewer-role
rules:
- apiGroups:
  - api.morpheusph.io
  resources:
  - nginxsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.morpheusph.io
  resources:
  - nginxsets/status
  verbs:
  - get
