apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        env:
        - name: pgdb
          value: 10.78.154.80
        - name: mq
          value: 10.78.154.81
        - name: domain
          value: morphy-10-78-154-200.nip.io
