apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  type: prod

resources:
- ../../base

patchesStrategicMerge:
- ingress.yaml
- deployment.yaml


patches:
- target:
    kind: Ingress
    name: nginx-ingress
  path: ingress-patch.json

images:
- name: docker.io/nginx
  newTag: 1.23.2
