apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/dev
    repoURL: https://github.com/MorpheusPH/kubernetes-study.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
