apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  type: dev

resources:
- ../../base

patchesStrategicMerge:
- ingress.yaml
- service.yaml

images:
- name: nginx
  newTag: stable