apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server}}
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.8.2
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
      values: |
        extraArgs: 
          - --enable-certificate-owner-ref=true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

