apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: morpheusph-io-ca
  namespace: default
spec:
  isCA: true
  commonName: morpheusph.io
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: morpheusph-io-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
